package charmaps

var ASCII = []Pattern{
	MustNewPattern(" ", "\n        \n        \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("!", "\n        \n   X    \n   X    \n   X    \n   X    \n        \n   X    \n        "),
	MustNewPattern("\"", "\n  X  X  \n  X  X  \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("#", "\n        \n  X  X  \n  X  X  \n XXX XX \n XX XXX \n  X  X  \n  X  X  \n        "),
	MustNewPattern("$", "\n   X    \n   X    \n XXXXX  \nX  X    \n XXXXXX \n   X  X \n XXXXX  \n   X    "),
	MustNewPattern("%", "\n        \n XX  X  \n XX X   \n   XX   \n  XX    \n  X XX  \n X  XX  \n        "),
	MustNewPattern("&", "\n        \n   XX   \n  X  X  \n  XXX   \n X  X X \n X   X  \n  XXX X \n        "),
	MustNewPattern("'", "\n   X    \n   X    \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("(", "\n        \n   XX   \n  X     \n  X     \n  X     \n  X     \n   XX   \n        "),
	MustNewPattern(")", "\n        \n  XX    \n    X   \n    X   \n    X   \n    X   \n  XX    \n        "),
	MustNewPattern("*", "\n        \n        \n        \n  XXXX  \n XXXXXX \n  X  X  \n        \n        "),
	MustNewPattern("+", "\n        \n        \n        \n   X    \n XXXXX  \n   X    \n        \n        "),
	MustNewPattern(",", "\n        \n        \n        \n        \n        \n        \n   X    \n  X     "),
	MustNewPattern("-", "\n        \n        \n        \n        \n XXXXXX \n        \n        \n        "),
	MustNewPattern(".", "\n        \n        \n        \n        \n        \n        \n   X    \n        "),
	MustNewPattern("/", "\n        \n     X  \n    X   \n   XX   \n  XX    \n  X     \n X      \n        "),
	MustNewPattern("0", "\n        \n  XXXX  \n X    X \n X  XXX \n XXX  X \n X    X \n  XXXX  \n        "),
	MustNewPattern("1", "\n        \n   XX   \n  X X   \n    X   \n    X   \n    X   \n  XXXXX \n        "),
	MustNewPattern("2", "\n        \n  XXXX  \n X    X \n     XX \n   XX   \n  X     \n XXXXXX \n        "),
	MustNewPattern("3", "\n        \n  XXXX  \n X    X \n   XXX  \n      X \n X    X \n  XXXX  \n        "),
	MustNewPattern("4", "\n        \n     XX \n   XX X \n  X   X \n XXXXXX \n      X \n      X \n        "),
	MustNewPattern("5", "\n        \n XXXXXX \n X      \n XXXXX  \n      X \n X    X \n  XXXX  \n        "),
	MustNewPattern("6", "\n        \n  XXXX  \n X      \n XXXXX  \n X    X \n X    X \n  XXXX  \n        "),
	MustNewPattern("7", "\n        \n XXXXXX \n      X \n     X  \n    X   \n   X    \n   X    \n        "),
	MustNewPattern("8", "\n        \n  XXXX  \n X    X \n  XXXX  \n X    X \n X    X \n  XXXX  \n        "),
	MustNewPattern("9", "\n        \n  XXXX  \n X    X \n X    X \n  XXXXX \n      X \n  XXXX  \n        "),
	MustNewPattern(":", "\n        \n        \n        \n   X    \n        \n        \n   X    \n        "),
	MustNewPattern(";", "\n        \n        \n        \n   X    \n        \n        \n   X    \n  X     "),
	MustNewPattern("<", "\n        \n     X  \n    X   \n  XX    \n XX     \n   XX   \n     X  \n        "),
	MustNewPattern("=", "\n        \n        \n        \n XXXXXX \n XXXXXX \n        \n        \n        "),
	MustNewPattern(">", "\n        \n X      \n  X     \n   XX   \n    XX  \n  XX    \n X      \n        "),
	MustNewPattern("?", "\n        \n  XXXX  \n X    X \n X   XX \n    X   \n        \n    X   \n        "),
	MustNewPattern("@", "\n        \n XXXXX  \nX     X \nX XXX X \nX X  XX \nX  XX   \n XXXXXX \n        "),
	MustNewPattern("A", "\n        \n  XXXX  \n X    X \n X    X \n XXXXXX \n X    X \n X    X \n        "),
	MustNewPattern("B", "\n        \n XXXXX  \n X    X \n XXXXX  \n X    X \n X    X \n XXXXX  \n        "),
	MustNewPattern("C", "\n        \n  XXXX  \n X    X \n X      \n X      \n X    X \n  XXXX  \n        "),
	MustNewPattern("D", "\n        \n XXXXX  \n X    X \n X    X \n X    X \n X    X \n XXXXX  \n        "),
	MustNewPattern("E", "\n        \n XXXXXX \n X      \n XXXX   \n X      \n X      \n XXXXXX \n        "),
	MustNewPattern("F", "\n        \n XXXXXX \n X      \n XXXX   \n X      \n X      \n X      \n        "),
	MustNewPattern("G", "\n        \n  XXXX  \n X    X \n X      \n X  XXX \n X    X \n  XXXX  \n        "),
	MustNewPattern("H", "\n        \n X    X \n X    X \n XXXXXX \n X    X \n X    X \n X    X \n        "),
	MustNewPattern("I", "\n        \n  XXX   \n   X    \n   X    \n   X    \n   X    \n  XXX   \n        "),
	MustNewPattern("J", "\n        \n    XXX \n     X  \n     X  \n     X  \n X   X  \n  XXX   \n        "),
	MustNewPattern("K", "\n        \n X    X \n X  XX  \n XXX    \n XXX    \n X  XX  \n X    X \n        "),
	MustNewPattern("L", "\n        \n X      \n X      \n X      \n X      \n X      \n XXXXXX \n        "),
	MustNewPattern("M", "\n        \nXX   XX \nX X X X \nX  X  X \nX     X \nX     X \nX     X \n        "),
	MustNewPattern("N", "\n        \n X    X \n XX   X \n X X  X \n X  X X \n X   XX \n X    X \n        "),
	MustNewPattern("O", "\n        \n  XXXX  \n X    X \n X    X \n X    X \n X    X \n  XXXX  \n        "),
	MustNewPattern("P", "\n        \n XXXXX  \n X    X \n X    X \n XXXXX  \n X      \n X      \n        "),
	MustNewPattern("Q", "\n        \n  XXXX  \n X    X \n X    X \n X    X \n X    X \n  XXXX  \n      X "),
	MustNewPattern("R", "\n        \n XXXXX  \n X    X \n X    X \n XXXXX  \n X  XX  \n X    X \n        "),
	MustNewPattern("S", "\n        \n  XXXX  \n X    X \n XXXXX  \n      X \n X    X \n  XXXX  \n        "),
	MustNewPattern("T", "\n        \nXXXXXXX \n   X    \n   X    \n   X    \n   X    \n   X    \n        "),
	MustNewPattern("U", "\n        \n X    X \n X    X \n X    X \n X    X \n X    X \n  XXXX  \n        "),
	MustNewPattern("V", "\n        \n X    X \n X    X \n X    X \n  X  X  \n  X  X  \n   XX   \n        "),
	MustNewPattern("W", "\n        \nX     X \nX     X \nX     X \nX  X  X \nX X X X \nXX   XX \n        "),
	MustNewPattern("X", "\n        \n X    X \n  X  X  \n   XX   \n   XX   \n  X  X  \n X    X \n        "),
	MustNewPattern("Y", "\n        \nX     X \n X   X  \n XX XX  \n   X    \n   X    \n   X    \n        "),
	MustNewPattern("Z", "\n        \n XXXXXX \n      X \n    XX  \n  XX    \n X      \n XXXXXX \n        "),
	MustNewPattern("[", "\n        \n  XXX   \n  X     \n  X     \n  X     \n  X     \n  XXX   \n        "),
	MustNewPattern("\\", "\n        \n X      \n  X     \n  XX    \n   XX   \n    X   \n     X  \n        "),
	MustNewPattern("]", "\n        \n  XXX   \n    X   \n    X   \n    X   \n    X   \n  XXX   \n        "),
	MustNewPattern("^", "\n   X    \n  X X   \n X   X  \n        \n        \n        \n        \n        "),
	MustNewPattern("_", "\n        \n        \n        \n        \n        \n        \n        \n XXXXXX "),
	MustNewPattern("`", "\n   XX   \n        \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("a", "\n        \n        \n        \n  XXXXX \n XXXXXX \n X    X \n  XXXXX \n        "),
	MustNewPattern("b", "\n        \n X      \n X      \n XXXXXX \n X    X \n X    X \n XXXXX  \n        "),
	MustNewPattern("c", "\n        \n        \n        \n XXXXXX \n X      \n X    X \n  XXXX  \n        "),
	MustNewPattern("d", "\n        \n      X \n      X \n XXXXXX \n X    X \n X    X \n  XXXXX \n        "),
	MustNewPattern("e", "\n        \n        \n        \n XXXXXX \n X XX X \n X      \n  XXXX  \n        "),
	MustNewPattern("f", "\n        \n    XXX \n   X    \n XXXXX  \n   X    \n   X    \n   X    \n        "),
	MustNewPattern("g", "\n        \n        \n        \n XXXXXX \n X    X \n X    X \n  XXXXX \n  XXXX  "),
	MustNewPattern("h", "\n        \n X      \n X      \n XXXXXX \n X    X \n X    X \n X    X \n        "),
	MustNewPattern("i", "\n        \n   X    \n        \n  XX    \n   X    \n   X    \n  XXX   \n        "),
	MustNewPattern("j", "\n        \n     X  \n        \n    XX  \n     X  \n     X  \n X   X  \n  XXX   "),
	MustNewPattern("k", "\n        \n X      \n X      \n X   XX \n XXXX   \n X  X   \n X   XX \n        "),
	MustNewPattern("l", "\n        \n  XX    \n   X    \n   X    \n   X    \n   X    \n  XXX   \n        "),
	MustNewPattern("m", "\n        \n        \n        \nXXXXXXX \nX  X  X \nX  X  X \nX  X  X \n        "),
	MustNewPattern("n", "\n        \n        \n        \n XXXXXX \n X    X \n X    X \n X    X \n        "),
	MustNewPattern("o", "\n        \n        \n        \n XXXXXX \n X    X \n X    X \n  XXXX  \n        "),
	MustNewPattern("p", "\n        \n        \n        \n XXXXXX \n X    X \n X    X \n XXXXX  \n X      "),
	MustNewPattern("q", "\n        \n        \n        \n XXXXXX \n X    X \n X    X \n  XXXXX \n      X "),
	MustNewPattern("r", "\n        \n        \n        \n XXXXXX \n X      \n X      \n X      \n        "),
	MustNewPattern("s", "\n        \n        \n        \n XXXXXX \n XXXXX  \n      X \n XXXXX  \n        "),
	MustNewPattern("t", "\n        \n   X    \n   X    \n XXXXX  \n   X    \n   X    \n    XXX \n        "),
	MustNewPattern("u", "\n        \n        \n        \n X    X \n X    X \n X    X \n  XXXXX \n        "),
	MustNewPattern("v", "\n        \n        \n        \n X    X \n XX  XX \n  X  X  \n   XX   \n        "),
	MustNewPattern("w", "\n        \n        \n        \nX     X \nX  X  X \nX  X  X \n XXXXX  \n        "),
	MustNewPattern("x", "\n        \n        \n        \n X    X \n  XXXX  \n  X  X  \n X    X \n        "),
	MustNewPattern("y", "\n        \n        \n        \n X    X \n X    X \n X    X \n  XXXXX \n  XXXX  "),
	MustNewPattern("z", "\n        \n        \n        \n XXXXXX \n    XX  \n  XX    \n XXXXXX \n        "),
	MustNewPattern("{", "\n        \n    XX  \n   X    \n  X     \n   X    \n   X    \n    XX  \n        "),
	MustNewPattern("|", "\n        \n   X    \n   X    \n   X    \n   X    \n   X    \n   X    \n        "),
	MustNewPattern("}", "\n        \n  XX    \n    X   \n     X  \n    X   \n    X   \n  XX    \n        "),
	MustNewPattern("~", "\n XX   X \nX  XXX  \n        \n        \n        \n        \n        \n        "),
}
