package charmaps

var BlocksBasic = []Pattern{
	MustNewPattern("▂", "\n        \n        \n        \n        \n        \n        \nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▀", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n        \n        \n        \n        "),
	MustNewPattern("▁", "\n        \n        \n        \n        \n        \n        \n        \nXXXXXXXX"),
	MustNewPattern("▃", "\n        \n        \n        \n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▄", "\n        \n        \n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▅", "\n        \n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▆", "\n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▇", "\n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("█", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▉", "\nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX "),
	MustNewPattern("▊", "\nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  "),
	MustNewPattern("▋", "\nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   "),
	MustNewPattern("▌", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▍", "\nXXX     \nXXX     \nXXX     \nXXX     \nXXX     \nXXX     \nXXX     \nXXX     "),
	MustNewPattern("▎", "\nXX      \nXX      \nXX      \nXX      \nXX      \nXX      \nXX      \nXX      "),
	MustNewPattern("▏", "\nX       \nX       \nX       \nX       \nX       \nX       \nX       \nX       "),
	MustNewPattern("▐", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▔", "\nXXXXXXXX\n        \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("▕", "\n       X\n       X\n       X\n       X\n       X\n       X\n       X\n       X"),
	MustNewPattern("▖", "\n        \n        \n        \n        \nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▗", "\n        \n        \n        \n        \n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▘", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \n        \n        \n        \n        "),
	MustNewPattern("▙", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▚", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▛", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▜", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▝", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n        \n        \n        \n        "),
	MustNewPattern("▞", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▟", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("█", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
}

var Blocks = []Pattern{
	MustNewPattern(" ", "\n        \n        \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("▂", "\n        \n        \n        \n        \n        \n        \nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▀", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n        \n        \n        \n        "),
	MustNewPattern("▁", "\n        \n        \n        \n        \n        \n        \n        \nXXXXXXXX"),
	MustNewPattern("▃", "\n        \n        \n        \n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▄", "\n        \n        \n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▅", "\n        \n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▆", "\n        \n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▇", "\n        \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("█", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▉", "\nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX \nXXXXXXX "),
	MustNewPattern("▊", "\nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  \nXXXXXX  "),
	MustNewPattern("▋", "\nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   \nXXXXX   "),
	MustNewPattern("▌", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▍", "\nXXX     \nXXX     \nXXX     \nXXX     \nXXX     \nXXX     \nXXX     \nXXX     "),
	MustNewPattern("▎", "\nXX      \nXX      \nXX      \nXX      \nXX      \nXX      \nXX      \nXX      "),
	MustNewPattern("▏", "\nX       \nX       \nX       \nX       \nX       \nX       \nX       \nX       "),
	MustNewPattern("▐", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▔", "\nXXXXXXXX\n        \n        \n        \n        \n        \n        \n        "),
	MustNewPattern("▕", "\n       X\n       X\n       X\n       X\n       X\n       X\n       X\n       X"),
	MustNewPattern("▖", "\n        \n        \n        \n        \nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▗", "\n        \n        \n        \n        \n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▘", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \n        \n        \n        \n        "),
	MustNewPattern("▙", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("▚", "\nXXXX    \nXXXX    \nXXXX    \nXXXX    \n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▛", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▜", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n    XXXX\n    XXXX\n    XXXX\n    XXXX"),
	MustNewPattern("▝", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\n        \n        \n        \n        "),
	MustNewPattern("▞", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\nXXXX    \nXXXX    \nXXXX    \nXXXX    "),
	MustNewPattern("▟", "\n    XXXX\n    XXXX\n    XXXX\n    XXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("─", "\n        \n        \n        \n        \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("━", "\n        \n        \n        \nXXXXXXXX\nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("│", "\n    X   \n    X   \n    X   \n    X   \n    X   \n    X   \n    X   \n    X   "),
	MustNewPattern("┃", "\n   XX   \n   XX   \n   XX   \n   XX   \n   XX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┄", "\n        \n        \n        \n        \nXX XX XX\n        \n        \n        "),
	MustNewPattern("┅", "\n        \n        \n        \nXX XX XX\nXX XX XX\n        \n        \n        "),
	MustNewPattern("┆", "\n    X   \n    X   \n        \n    X   \n    X   \n        \n    X   \n    X   "),
	MustNewPattern("┇", "\n   XX   \n   XX   \n        \n   XX   \n   XX   \n        \n   XX   \n   XX   "),
	MustNewPattern("┈", "\n        \n        \n        \n        \nX X X X \n        \n        \n        "),
	MustNewPattern("┉", "\n        \n        \n        \nX X X X \nX X X X \n        \n        \n        "),
	MustNewPattern("┊", "\n    X   \n        \n    X   \n        \n    X   \n        \n    X   \n        "),
	MustNewPattern("┋", "\n   XX   \n        \n   XX   \n        \n   XX   \n        \n   XX   \n        "),
	MustNewPattern("┌", "\n        \n        \n        \n        \n    XXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┍", "\n        \n        \n        \n    XXXX\n    XXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┎", "\n        \n        \n        \n        \n   XXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┏", "\n        \n        \n        \n   XXXXX\n   XXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┐", "\n        \n        \n        \n        \nXXXXX   \n    X   \n    X   \n    X   "),
	MustNewPattern("┑", "\n        \n        \n        \nXXXXX   \nXXXXX   \n    X   \n    X   \n    X   "),
	MustNewPattern("┒", "\n        \n        \n        \n        \nXXXXX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┓", "\n        \n        \n        \nXXXXX   \nXXXXX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("└", "\n    X   \n    X   \n    X   \n    X   \n    XXXX\n        \n        \n        "),
	MustNewPattern("┕", "\n    X   \n    X   \n    X   \n    XXXX\n    XXXX\n        \n        \n        "),
	MustNewPattern("┖", "\n   XX   \n   XX   \n   XX   \n   XX   \n   XXXXX\n        \n        \n        "),
	MustNewPattern("┗", "\n   XX   \n   XX   \n   XX   \n   XXXXX\n   XXXXX\n        \n        \n        "),
	MustNewPattern("┘", "\n    X   \n    X   \n    X   \n    X   \nXXXXX   \n        \n        \n        "),
	MustNewPattern("┙", "\n    X   \n    X   \n    X   \nXXXXX   \nXXXXX   \n        \n        \n        "),
	MustNewPattern("┚", "\n   XX   \n   XX   \n   XX   \n   XX   \nXXXXX   \n        \n        \n        "),
	MustNewPattern("┛", "\n   XX   \n   XX   \n   XX   \nXXXXX   \nXXXXX   \n        \n        \n        "),
	MustNewPattern("├", "\n    X   \n    X   \n    X   \n    X   \n    XXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┝", "\n    X   \n    X   \n    X   \n    XXXX\n    XXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┞", "\n   XX   \n   XX   \n   XX   \n   XX   \n   XXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┟", "\n    X   \n    X   \n    X   \n    X   \n   XXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┠", "\n   XX   \n   XX   \n   XX   \n   XX   \n   XXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┡", "\n   XX   \n   XX   \n   XX   \n   XXXXX\n   XXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┢", "\n    X   \n    X   \n    X   \n   XXXXX\n   XXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┣", "\n   XX   \n   XX   \n   XX   \n   XXXXX\n   XXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┤", "\n    X   \n    X   \n    X   \n    X   \nXXXXX   \n    X   \n    X   \n    X   "),
	MustNewPattern("┥", "\n    X   \n    X   \n    X   \nXXXXX   \nXXXXX   \n    X   \n    X   \n    X   "),
	MustNewPattern("┦", "\n   XX   \n   XX   \n   XX   \n   XX   \nXXXXX   \n    X   \n    X   \n    X   "),
	MustNewPattern("┧", "\n    X   \n    X   \n    X   \n    X   \nXXXXX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┨", "\n   XX   \n   XX   \n   XX   \n   XX   \nXXXXX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┩", "\n   XX   \n   XX   \n   XX   \nXXXXX   \nXXXXX   \n    X   \n    X   \n    X   "),
	MustNewPattern("┪", "\n    X   \n    X   \n    X   \nXXXXX   \nXXXXX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┫", "\n   XX   \n   XX   \n   XX   \nXXXXX   \nXXXXX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┬", "\n        \n        \n        \n        \nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┭", "\n        \n        \n        \nXXXXX   \nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┮", "\n        \n        \n        \n    XXXX\nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┯", "\n        \n        \n        \nXXXXXXXX\nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┰", "\n        \n        \n        \n        \nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┱", "\n        \n        \n        \nXXXXX   \nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┲", "\n        \n        \n        \n   XXXXX\nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┳", "\n        \n        \n        \nXXXXXXXX\nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("┴", "\n    X   \n    X   \n    X   \n    X   \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┵", "\n    X   \n    X   \n    X   \nXXXXX   \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┶", "\n    X   \n    X   \n    X   \n    XXXX\nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┷", "\n    X   \n    X   \n    X   \nXXXXXXXX\nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┸", "\n   XX   \n   XX   \n   XX   \n   XX   \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┹", "\n   XX   \n   XX   \n   XX   \nXXXXX   \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┺", "\n   XX   \n   XX   \n   XX   \n   XXXXX\nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┻", "\n   XX   \n   XX   \n   XX   \nXXXXXXXX\nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("┼", "\n    X   \n    X   \n    X   \n    X   \nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┽", "\n    X   \n    X   \n    X   \nXXXXX   \nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┾", "\n    X   \n    X   \n    X   \n    XXXX\nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("┿", "\n    X   \n    X   \n    X   \nXXXXXXXX\nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("╀", "\n   XX   \n   XX   \n   XX   \n   XX   \nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("╁", "\n    X   \n    X   \n    X   \n    X   \nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╂", "\n   XX   \n   XX   \n   XX   \n   XX   \nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╃", "\n   XX   \n   XX   \n   XX   \nXXXXX   \nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("╄", "\n   XX   \n   XX   \n   XX   \n   XXXXX\nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("╅", "\n    X   \n    X   \n    X   \nXXXXX   \nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╆", "\n    X   \n    X   \n    X   \n   XXXXX\nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╇", "\n   XX   \n   XX   \n   XX   \nXXXXXXXX\nXXXXXXXX\n    X   \n    X   \n    X   "),
	MustNewPattern("╈", "\n    X   \n    X   \n    X   \nXXXXXXXX\nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╉", "\n   XX   \n   XX   \n   XX   \nXXXXX   \nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╊", "\n   XX   \n   XX   \n   XX   \n   XXXXX\nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╋", "\n   XX   \n   XX   \n   XX   \nXXXXXXXX\nXXXXXXXX\n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╌", "\n        \n        \n        \n        \nXXX  XXX\n        \n        \n        "),
	MustNewPattern("╍", "\n        \n        \n        \nXXX  XXX\nXXX  XXX\n        \n        \n        "),
	MustNewPattern("╎", "\n    X   \n    X   \n    X   \n        \n        \n    X   \n    X   \n    X   "),
	MustNewPattern("╏", "\n   XX   \n   XX   \n   XX   \n        \n        \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╱", "\n       X\n      X \n     X  \n    X   \n   X    \n  X     \n X      \nX       "),
	MustNewPattern("╱", "\n      XX\n     XXX\n    XXX \n   XXX  \n  XXX   \n XXX    \nXXX     \nXX      "),
	MustNewPattern("╲", "\nX       \n X      \n  X     \n   X    \n    X   \n     X  \n      X \n       X"),
	MustNewPattern("╲", "\nXX      \nXXX     \n XXX    \n  XXX   \n   XXX  \n    XXX \n     XXX\n      XX"),
	MustNewPattern("╳", "\nX      X\n X    X \n  X  X  \n   XX   \n   XX   \n  X  X  \n X    X \nX      X"),
	MustNewPattern("╴", "\n        \n        \n        \n        \nXXXX    \n        \n        \n        "),
	MustNewPattern("╵", "\n    X   \n    X   \n    X   \n    X   \n        \n        \n        \n        "),
	MustNewPattern("╶", "\n        \n        \n        \n        \n    XXXX\n        \n        \n        "),
	MustNewPattern("╷", "\n        \n        \n        \n        \n    X   \n    X   \n    X   \n    X   "),
	MustNewPattern("╸", "\n        \n        \n        \nXXXX    \nXXXX    \n        \n        \n        "),
	MustNewPattern("╹", "\n   XX   \n   XX   \n   XX   \n   XX   \n        \n        \n        \n        "),
	MustNewPattern("╺", "\n        \n        \n        \n    XXXX\n    XXXX\n        \n        \n        "),
	MustNewPattern("╻", "\n        \n        \n        \n        \n   XX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╼", "\n        \n        \n        \n    XXXX\nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("╽", "\n    X   \n    X   \n    X   \n    X   \n   XX   \n   XX   \n   XX   \n   XX   "),
	MustNewPattern("╾", "\n        \n        \n        \nXXXX    \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("╿", "\n   XX   \n   XX   \n   XX   \n   XX   \n    X   \n    X   \n    X   \n    X   "),
	MustNewPattern("░", "\nX   X   \n  X   X \nX   X   \n  X   X \nX   X   \n  X   X \nX   X   \n  X   X "),
	MustNewPattern("▒", "\nX X X X \n X X X X\nX X X X \n X X X X\nX X X X \n X X X X\nX X X X \n X X X X"),
	MustNewPattern("▓", "\n XXX XXX\nXX XXX X\n XXX XXX\nXX XXX X\n XXX XXX\nXX XXX X\n XXX XXX\nXX XXX X"),
	MustNewPattern("🮘", "\nX  X  X \n X  X  X\n  X  X  \nX  X  X \n X  X  X\n  X  X  \nX  X  X \n X  X  X"),
	MustNewPattern("🮙", "\n X  X  X\nX  X  X \n  X  X  \n X  X  X\nX  X  X \n  X  X  \n X  X  X\nX  X  X "),
	MustNewPattern("🭼", "\nX       \nX       \nX       \nX       \nX       \nX       \nX       \nXXXXXXXX"),
	MustNewPattern("🭽", "\nXXXXXXXX\nX       \nX       \nX       \nX       \nX       \nX       \nX       "),
	MustNewPattern("🭾", "\nXXXXXXXX\n       X\n       X\n       X\n       X\n       X\n       X\n       X"),
	MustNewPattern("🭿", "\n       X\n       X\n       X\n       X\n       X\n       X\n       X\nXXXXXXXX"),
	MustNewPattern("🮀", "\nXXXXXXXX\n        \n        \n        \n        \n        \n        \nXXXXXXXX"),
	MustNewPattern("🭰", "\n X      \n X      \n X      \n X      \n X      \n X      \n X      \n X      "),
	MustNewPattern("🭱", "\n  X     \n  X     \n  X     \n  X     \n  X     \n  X     \n  X     \n  X     "),
	MustNewPattern("🭲", "\n   X    \n   X    \n   X    \n   X    \n   X    \n   X    \n   X    \n   X    "),
	MustNewPattern("🭳", "\n    X   \n    X   \n    X   \n    X   \n    X   \n    X   \n    X   \n    X   "),
	MustNewPattern("🭴", "\n     X  \n     X  \n     X  \n     X  \n     X  \n     X  \n     X  \n     X  "),
	MustNewPattern("🭵", "\n      X \n      X \n      X \n      X \n      X \n      X \n      X \n      X "),
	MustNewPattern("🭶", "\n        \nXXXXXXXX\n        \n        \n        \n        \n        \n        "),
	MustNewPattern("🭷", "\n        \n        \nXXXXXXXX\n        \n        \n        \n        \n        "),
	MustNewPattern("🭸", "\n        \n        \n        \nXXXXXXXX\n        \n        \n        \n        "),
	MustNewPattern("🭹", "\n        \n        \n        \n        \nXXXXXXXX\n        \n        \n        "),
	MustNewPattern("🭺", "\n        \n        \n        \n        \n        \nXXXXXXXX\n        \n        "),
	MustNewPattern("🭻", "\n        \n        \n        \n        \n        \n        \nXXXXXXXX\n        "),
	MustNewPattern("🮕", "\nXX  XX  \nXX  XX  \n  XX  XX\n  XX  XX\nXX  XX  \nXX  XX  \n  XX  XX\n  XX  XX"),
	MustNewPattern("🮖", "\n  XX  XX\n  XX  XX\nXX  XX  \nXX  XX  \n  XX  XX\n  XX  XX\nXX  XX  \nXX  XX  "),
	MustNewPattern("🮗", "\n        \n        \nXXXXXXXX\nXXXXXXXX\n        \n        \nXXXXXXXX\nXXXXXXXX"),
}

var BlocksAdvanced = []Pattern{
	MustNewPattern("🬼", "\n        \n        \n        \n        \n        \nX       \nXXX     \nXXXX    "),
	MustNewPattern("🬽", "\n        \n        \n        \n        \n        \nXX      \nXXXXX   \nXXXXXXXX"),
	MustNewPattern("🬾", "\n        \n        \n        \nX       \nXX      \nXX      \nXXX     \nXXXX    "),
	MustNewPattern("🬿", "\n        \n        \n        \nXX      \nXXX     \nXXXXX   \nXXXXXXX \nXXXXXXXX"),
	MustNewPattern("🭀", "\n        \nX       \nX       \nXX      \nXX      \nXXX     \nXXX     \nXXXX    "),
	MustNewPattern("🭁", "\n    XXXX\n   XXXXX\n XXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭂", "\n        \n     XXX\n  XXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭃", "\n    XXXX\n   XXXXX\n   XXXXX\n  XXXXXX\n XXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭄", "\n        \n       X\n      XX\n    XXXX\n  XXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭅", "\n    XXXX\n    XXXX\n   XXXXX\n   XXXXX\n  XXXXXX\n  XXXXXX\n XXXXXXX\n XXXXXXX"),
	MustNewPattern("🭆", "\n        \n        \n        \n     XXX\n   XXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭇", "\n        \n        \n        \n        \n        \n       X\n     XXX\n    XXXX"),
	MustNewPattern("🭈", "\n        \n        \n        \n        \n        \n      XX\n   XXXXX\n XXXXXXX"),
	MustNewPattern("🭉", "\n        \n        \n        \n       X\n      XX\n      XX\n     XXX\n    XXXX"),
	MustNewPattern("🭊", "\n        \n        \n        \n       X\n     XXX\n   XXXXX\n XXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭋", "\n       X\n       X\n      XX\n      XX\n     XXX\n     XXX\n    XXXX\n    XXXX"),
	MustNewPattern("🭌", "\nXXXX    \nXXXXXX  \nXXXXXXX \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭍", "\nX       \nXXX     \nXXXXXX  \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭎", "\nXXXX    \nXXXXX   \nXXXXXX  \nXXXXXX  \nXXXXXXX \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭏", "\nX       \nXX      \nXXXX    \nXXXXXX  \nXXXXXXX \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭐", "\nXXXX    \nXXXX    \nXXXXX   \nXXXXX   \nXXXXXX  \nXXXXXX  \nXXXXXXX \nXXXXXXX "),
	MustNewPattern("🭑", "\n        \n        \n        \nXXX     \nXXXXX   \nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭒", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n XXXXXXX\n   XXXXX\n    XXXX"),
	MustNewPattern("🭓", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n  XXXXXX\n     XXX\n        "),
	MustNewPattern("🭔", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n XXXXXXX\n  XXXXXX\n  XXXXXX\n   XXXXX\n   XXXXX"),
	MustNewPattern("🭕", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n XXXXXXX\n  XXXXXX\n    XXXX\n     XXX\n       X"),
	MustNewPattern("🭖", "\n XXXXXXX\n XXXXXXX\n  XXXXXX\n  XXXXXX\n   XXXXX\n   XXXXX\n    XXXX\n    XXXX"),
	MustNewPattern("🭗", "\nXXXX    \nXXX     \nX       \n        \n        \n        \n        \n        "),
	MustNewPattern("🭘", "\nXXXXXXXX\nXXXXX   \nXXX     \n        \n        \n        \n        \n        "),
	MustNewPattern("🭙", "\nXXXX    \nXXX     \nXXX     \nX       \nX       \n        \n        \n        "),
	MustNewPattern("🭚", "\nXXXXXXXX\nXXXXXXX \nXXXXX   \nXXX     \nXX      \n        \n        \n        "),
	MustNewPattern("🭛", "\nXXXX    \nXXXX    \nXXX     \nXXX     \nXX      \nX       \nX       \n        "),
	MustNewPattern("🭜", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXX   \nXXX     \n        \n        \n        "),
	MustNewPattern("🭝", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXX \nXXXXXX  \nXXXX    "),
	MustNewPattern("🭞", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXX  \nXXX     \nX       "),
	MustNewPattern("🭟", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXX \nXXXXXXX \nXXXXXX  \nXXXXX   \nXXXX    "),
	MustNewPattern("🭠", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXX \nXXXXXX  \nXXXX    \nXXX     \nX       "),
	MustNewPattern("🭡", "\nXXXXXXX \nXXXXXXX \nXXXXXX  \nXXXXXX  \nXXXXX   \nXXXXX   \nXXXX    \nXXXX    "),
	MustNewPattern("🭢", "\n    XXXX\n      XX\n       X\n        \n        \n        \n        \n        "),
	MustNewPattern("🭣", "\nXXXXXXXX\n   XXXXX\n      XX\n        \n        \n        \n        \n        "),
	MustNewPattern("🭤", "\n    XXXX\n     XXX\n      XX\n      XX\n       X\n        \n        \n        "),
	MustNewPattern("🭥", "\n XXXXXXX\n  XXXXXX\n    XXXX\n     XXX\n       X\n        \n        \n        "),
	MustNewPattern("🭦", "\n    XXXX\n    XXXX\n     XXX\n     XXX\n      XX\n      XX\n       X\n       X"),
	MustNewPattern("🭧", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\n   XXXXX\n     XXX\n        \n        \n        "),
	MustNewPattern("🭨", "\nXXXXXXXX\n XXXXXXX\n  XXXXXX\n   XXXXX\n    XXXX\n   XXXXX\n  XXXXXX\n XXXXXXX"),
	MustNewPattern("🭩", "\n        \nX      X\nXX    XX\nXXX  XXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX"),
	MustNewPattern("🭪", "\nXXXXXXXX\nXXXXXXX \nXXXXXX  \nXXXXX   \nXXXX    \nXXXXX   \nXXXXXX  \nXXXXXXX "),
	MustNewPattern("🭫", "\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXXXXXXX\nXXX  XXX\nXX    XX\nX      X\n        "),
	MustNewPattern("🭬", "\n        \nX       \nXX      \nXXX     \nXXXX    \nXXX     \nXX      \nX       "),
	MustNewPattern("🭭", "\nXXXXXXXX\n XXXXXX \n  XXXX  \n   XX   \n        \n        \n        \n        "),
	MustNewPattern("🭮", "\n        \n       X\n      XX\n     XXX\n    XXXX\n     XXX\n      XX\n       X"),
	MustNewPattern("🭯", "\n        \n        \n        \n        \n   XX   \n  XXXX  \n XXXXXX \nXXXXXXXX"),
	MustNewPattern("🮚", "\nXXXXXXX \n XXXXX  \n  XXX   \n   X    \n    X   \n   XXX  \n  XXXXX \n XXXXXXX"),
	MustNewPattern("🮛", "\n       X\nX     XX\nXX   XXX\nXXX XXXX\nXXXX XXX\nXXX   XX\nXX     X\nX       "),
	MustNewPattern("🮠", "\n   X    \n  X     \n X      \nX       \n        \n        \n        \n        "),
	MustNewPattern("🮡", "\n    X   \n     X  \n      X \n       X\n        \n        \n        \n        "),
	MustNewPattern("🮢", "\n        \n        \n        \n        \nX       \n X      \n  X     \n   X    "),
	MustNewPattern("🮣", "\n        \n        \n        \n        \n       X\n      X \n     X  \n    X   "),
	MustNewPattern("🮤", "\n   X    \n  X     \n X      \nX       \nX       \n X      \n  X     \n   X    "),
	MustNewPattern("🮥", "\n    X   \n     X  \n      X \n       X\n       X\n      X \n     X  \n    X   "),
	MustNewPattern("🮦", "\n        \n        \n        \n        \nX      X\n X    X \n  X  X  \n   XX   "),
	MustNewPattern("🮧", "\n   XX   \n  X  X  \n X    X \nX      X\n        \n        \n        \n        "),
	MustNewPattern("🮨", "\n   X    \n  X     \n X      \nX       \n       X\n      X \n     X  \n    X   "),
	MustNewPattern("🮩", "\n    X   \n     X  \n      X \n       X\nX       \n X      \n  X     \n   X    "),
	MustNewPattern("🮪", "\n    X   \n     X  \n      X \n       X\nX      X\n X    X \n  X  X  \n   XX   "),
	MustNewPattern("🮫", "\n   X    \n  X     \n X      \nX       \nX      X\n X    X \n  X  X  \n   XX   "),
	MustNewPattern("🮬", "\n   XX   \n  X  X  \n X    X \nX      X\n       X\n      X \n     X  \n    X   "),
	MustNewPattern("🮭", "\n   XX   \n  X  X  \n X    X \nX      X\nX       \n X      \n  X     \n   X    "),
	MustNewPattern("🮮", "\n   XX   \n  X  X  \n X    X \nX      X\nX      X\n X    X \n  X  X  \n   XX   "),
}
